from meet_shuffler import *

#making section a
sectiona = Section("sectionb")
#section A students
sectiona.add_student(Student("Tomer","I","M"))
sectiona.add_student(Student("Robert","I","M"))
sectiona.add_student(Student("Yotam","I","M"))
sectiona.add_student(Student("Einav","I","F"))
sectiona.add_student(Student("Yuly","I","F"))
sectiona.add_student(Student("Shira","I","F"))
sectiona.add_student(Student("Adi","I","F"))
sectiona.add_student(Student("Nicole","I","F"))
sectiona.add_student(Student("Carlos","P","M"))
sectiona.add_student(Student("Amir Shahbari","P","M"))
sectiona.add_student(Student("Ramzi","P","M"))
sectiona.add_student(Student("Fouad","P","M"))
sectiona.add_student(Student("Amir S","P","M"))
sectiona.add_student(Student("Lyne","P","F"))
sectiona.add_student(Student("Leen","P","F"))
sectiona.add_student(Student("Marial","P","F"))
sectiona.add_student(Student("Malak","P","F"))
sectiona.add_student(Student("Luna","P","F"))
sectiona.add_student(Student("Hala","P","F"))
sectiona.add_student(Student("Siham","P","F"))



#making section B
sectionb = Section("sectionb")

#making all section B students (this is terrible code etiquette haaaa)
sectionb.add_student(Student("Guy","I","M"))
sectionb.add_student(Student("Hadar","I","M"))
sectionb.add_student(Student("Yonatan","I","M"))
sectionb.add_student(Student("Sivan","I","F"))
sectionb.add_student(Student("Gal","I","F"))
sectionb.add_student(Student("May","I","F"))
sectionb.add_student(Student("Shaharit","I","F"))
sectionb.add_student(Student("Shira","I","F"))
sectionb.add_student(Student("George","P","M"))
sectionb.add_student(Student("Nasif","P","M"))
sectionb.add_student(Student("Rajai","P","M"))
sectionb.add_student(Student("Yazn","P","M"))
sectionb.add_student(Student("Ade","P","M"))
sectionb.add_student(Student("Chris","P","M"))
sectionb.add_student(Student("Malak","P","F"))
sectionb.add_student(Student("Hala","P","F"))
sectionb.add_student(Student("Layan","P","F"))
sectionb.add_student(Student("Dana","P","F"))
sectionb.add_student(Student("Nisreen","P","F"))
sectionb.add_student(Student("Michella","P","F"))

#making section C
sectionc = Section("sectionc")

#adding section C
sectionc.add_student(Student("Gilead","I","M"))
sectionc.add_student(Student("Ben","I","M"))
sectionc.add_student(Student("Noa T","I","F"))
sectionc.add_student(Student("Noa Hadad","I","F"))
sectionc.add_student(Student("Zohar","I","F"))
sectionc.add_student(Student("Alicia K","I","F"))
sectionc.add_student(Student("Neomy","I","F"))
sectionc.add_student(Student("Avigail","I","F"))
sectionc.add_student(Student("George","P","M"))
sectionc.add_student(Student("Naim","P","M"))
sectionc.add_student(Student("Mahd","P","M"))
sectionc.add_student(Student("Mahmood","P","M"))
sectionc.add_student(Student("Zain","P","M"))
sectionc.add_student(Student("Bassam","P","M"))
sectionc.add_student(Student("Warrd","P","F"))
sectionc.add_student(Student("Sham","P","F"))
sectionc.add_student(Student("Sama","P","F"))
sectionc.add_student(Student("Luna","P","F"))
sectionc.add_student(Student("Nadia","P","F"))
sectionc.add_student(Student("Alicia H","P","F"))
